apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
spec:
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: counter
        image: centos:7
        command: ["/bin/bash", "-c", "/path/to/your/main/entrypoint && curl -X POST https://172.104.10.245:6443/quitquitquit"]
      restartPolicy: Never